# Copyright (c) 2022-2023 IO-Aero. All rights reserved. Use of this
# source code is governed by the IO-Aero License, that can
# be found in the LICENSE.md file.

"""Module stub file."""

def initialise_logger() -> None: ...
def progress_msg(is_verbose: bool, msg: str) -> None: ...
def progress_msg_core(msg: str) -> None: ...
def terminate_fatal(error_msg: str) -> None: ...
