name: Python - Coveralls

on:
  pull_request:
    types: [closed]
    branches: [ 'main' ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  python_coveralls:
    # --------------------------------------------------------------------------
    # Create and store the coveralls results.
    # --------------------------------------------------------------------------
    name: OS ${{ matrix.os }} - Python ${{ matrix.python-version }} - Development Standards
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      matrix:
        os: ["ubuntu-22.04"]
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1  # no history, just HEAD
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Step - Necessary system software
        run: |
            sudo apt-get update -y
      - name: Install dev dependencies
        run: make pipenv-dev
      - name: Run the tests
        run: |
          git checkout main
          make pytest
      - name: Publish the code coverage to coveralls.io
        run: |
            echo "::echo::on"
            echo "================================================================================"
            echo "Current version of Python3: $(python --version)"
            echo "Current version of pip3: $(pip --version || true)"
            echo "Current version of Ubuntu: $(lsb_release -a)"
            echo "================================================================================"
            make coveralls
