name: Rust - Development

on:
  pull_request:
    types: [opened, reopened]
    branches: [ 'main' ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test_development:
    # --------------------------------------------------------------------------
    # Install the development environment and run all tests based on cargo test.
    # --------------------------------------------------------------------------
    name: OS ${{ matrix.os }} - Rust ${{ matrix.rust-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      matrix:
        os: ["ubuntu-20.04"]
        rust: ["1.70.0"]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1  # no history, just HEAD
      - name: Set up Rust ${{ matrix.rust-version }}
        uses: hecrj/setup-rust-action@master
        with:
          rust-version: ${{ matrix.rust }}
      - name: Install Step - Necessary system software
        run: |
            sudo apt-get update -y
      - name: Install dev dependencies
        run: rustup component add build clippy docs rustfmt test
      - name: Run the whole software quality chain
        run: |
            echo "::echo::on"
            echo "================================================================================"
            echo "Current version of Cargo:  $(cargo --version)"
            echo "Current version of Rust:   $(rustc --version)"
            echo "Current version of Ubuntu: $(lsb_release -a)"
            echo "================================================================================"
            make final-rust
