name: Test - Development

on:
  pull_request:
    types: [opened, reopened]
    branches: [ 'main' ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test_development:
    # --------------------------------------------------------------------------
    # Install the development environment and run all tests based on pytest.
    # --------------------------------------------------------------------------
    name: OS ${{ matrix.os }} - Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      matrix:
        os: ["ubuntu-20.04"]
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1  # no history, just HEAD
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dev dependencies
        run: make pipenv-dev
      - name: Install Step - Necessary system software (incl. GDAL & Rasterio)
        run: |
            sudo add-apt-repository ppa:ubuntugis/ppa
            sudo apt-get update -y
            sudo apt-get install -y gdal-bin \
                                    libgdal-dev \
                                    python-numpy
            python3 -m pipenv run pip install sua
            python3 -m pipenv run pip freeze
      - name: Compile the Python code
        run: make compileall
      - name: Run pytest for writing better program
        run: |
            echo "::echo::on"
            echo "================================================================================"
            echo "Current version of Python3: $(python --version)"
            echo "Current version of pip3: $(pip --version || true)"
            echo "Current version of Ubuntu: $(lsb_release -a)"
            echo "================================================================================"
            make pytest
